const paths={arrow:'M4 12h16m-7-7 7 7-7 7',external:'M7 17 17 7M7 7h10v10',down:'m6 9 6 6 6-6',close:'m6 6 12 12M18 6 6 18',plus:'M12 5v14M5 12h14',play:'m9 5 11 7-11 7Z',box:'m12 3 9 5v8l-9 5-9-5V8Zm-9 5 9 5 9-5M12 13v8M7.5 5.5l9 5',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M16 3a4 4 0 0 1 0 8M22 21v-2a4 4 0 0 0-3-3.87M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',phone:'M8 2h8a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2M11 18h2',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0M15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z',pen:'m4 16 12-12 4 4L8 20H4Zm10-10 4 4',camera:'M3 7h4l2-3h6l2 3h4v14H3ZM16 14a4 4 0 1 1-8 0 4 4 0 0 1 8 0',edit:'M4 4h16v16H4ZM4 9h16M9 4v5M15 4v5M4 15h16M9 15v5M15 15v5'};
function icon(name){return `<svg viewBox="0 0 24 24" fill="${name==='play'?'currentColor':'none'}" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]}"/></svg>`}
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const films=[
{id:'pilot',client:'PILOT WP',title:'Bez umowy. Bez anteny.',image:'pilot.webp',video:'kB_gIEpOXKs',cat:['produkt'],format:'Spot reklamowy / 15 s',description:'Trzy korzyści platformy zamknięte w krótkim, czytelnym komunikacie. Przygotowanie, zdjęcia i postprodukcja zrealizowane przez BBF.'},
{id:'fanex',client:'FANEX',title:'Hollywood / Sos Teriyaki',image:'Nocc64MIf-0.jpg',video:'Nocc64MIf-0',cat:['produkt','food'],format:'Film produktowy / 15 s',description:'Jeden z serii spotów Fanex emitowanych w Suntago. Produkt, apetyt i wyrazisty pomysł w krótkim formacie.'},
{id:'agh',client:'AGH',title:'Fascynują nas wasze błędy',image:'agh.webp',video:'Gd7pDtzLTFI',cat:['marka'],format:'Kampania wizerunkowa',description:'Film dla uczelni oparty na idei odkrywania przez próby i błędy. Charakter marki opowiedziany historią.'},
{id:'suempol',client:'SUEMPOL',title:'Gotowanie z Suempol',image:'Mynp4ZV_l0k.jpg',video:'Mynp4ZV_l0k',cat:['food','social'],format:'Program kulinarny',description:'Grillowany bakłażan z łososiem Coho. Przepis, produkt i przygotowanie dania w jednym odcinku programu.'},
{id:'vw',client:'VOLKSWAGEN',title:'Historia zakupu',image:'dCgproXrgE8.jpg',video:'dCgproXrgE8',cat:['produkt'],format:'Spot reklamowy / 15 s',description:'Historia zakupu w programie Volkswagen Certyfikowane Używane. Realizacja w ramach serii filmów motoryzacyjnych.',agency:'DRUM Poland'},
{id:'frens',client:'FRENS',title:'Randka z pieskiem',image:'ISxKiJYmMfk.jpg',video:'ISxKiJYmMfk',cat:['marka'],format:'Film społeczny',description:'Spot promujący wydarzenie „Randka z pieskiem”. Historia, która zaprasza do udziału i nadaje wydarzeniu emocjonalny kontekst.'},
{id:'praga',client:'M.ST. WARSZAWA',title:'Cinematic Praga',image:'praga.webp',video:'Sh7jShWrWlM',cat:['marka'],format:'Film promocyjny / Miejsce',description:'Praga-Północ opowiedziana obrazem. Film promujący warszawską dzielnicę, jej miejsca i atmosferę.'},
{id:'strabiscan',client:'CX ENGINEERING',title:'StrabiScan',image:'SBNOQinz1Y4.jpg',video:'SBNOQinz1Y4',cat:['produkt'],format:'Film o technologii',description:'Film o problemie zeza u dzieci i narzędziu do diagnozy choroby zezowej u najmłodszych - Strabiscan.'},
{id:'fanex-social',client:'FANEX',title:'Sos amerykański',image:'RXt7wRFEytI.jpg',video:'RXt7wRFEytI',cat:['food','social'],format:'Rolka produktowa / Pion',description:'Krótki film produktowy w klimacie westernu. Wyrazista konwencja w formacie do social mediów.',portrait:true},
{id:'gastrofan',client:'FANEX',title:'Gastrofan 2025',image:'gastrofan.webp',video:'N9zZweZIo2g',cat:['food','social'],format:'Kampania / Branded content',description:'Realizacja kampanii Gastrofan 2025 dla marki Fanex.'},
{id:'raszyn',client:'RASZYN',title:'Dożynki w Raszynie',image:'raszyn-dozynki.webp',video:'8sqozyNwaGY',cat:['social'],format:'Relacja z wydarzenia',description:'Ludzie, spotkania i atmosfera wydarzenia. Materiał z dożynek w Raszynie.'},
{id:'czas',client:'FUNDACJA URSZULI JAWORSKIEJ',title:'Czas nas goni',image:'mW_rk44x-Rk.jpg',video:'mW_rk44x-Rk',cat:['marka'],format:'Kampania społeczna',description:'Spot kampanii „Polska bez HCV” dla Fundacji Urszuli Jaworskiej.'}];
const showreel={id:'showreel',client:'BIG BEAR FILM',title:'Nasz showreel',image:'showreel.jpg',video:'aZxidOzdfUU',format:'Przekrój realizacji',description:'Reklama, produkt, ludzie i historie. Zobaczcie różne oblicza naszych produkcji.'};
const offers={
produkt:{number:'01',title:'NIECH PRODUKT<br>GRA GŁÓWNĄ ROLĘ.',intro:'Pokażcie, co sprzedajecie, jak to działa i dlaczego warto się tym zainteresować.',formats:['Spot reklamowy','Film produktowy','Food video'],points:['Pomysł oparty na jednej, czytelnej korzyści.','Produkt w użyciu, detale i ludzie przed kamerą.','Główny film i uzgodnione krótsze wersje do kampanii.'],film:'fanex',example:'PRODUKT W PRAKTYCE',result:'Na stronę, do reklamy i do social mediów.'},
marka:{number:'02',title:'POKAŻCIE,<br>CO ZA WAMI STOI.',intro:'Pozwólcie klientom poznać ludzi, sposób pracy i historię, które tworzą Waszą firmę.',formats:['Film wizerunkowy','Historia marki','Film o zespole'],points:['Pomagamy znaleźć temat i sposób opowiedzenia historii.','Łączymy wypowiedzi ludzi z obrazem ich pracy.','Budujemy spójny film z muzyką, montażem i kolorem.'],film:'agh',example:'MARKA Z WŁASNYM GŁOSEM',result:'Na stronę, prezentację i do komunikacji marki.'},
social:{number:'03',title:'JEDEN POMYSŁ.<br>WIĘCEJ DO POKAZANIA.',intro:'Zamiast pojedynczego filmu - seria materiałów, z których można korzystać w kolejnych publikacjach.',formats:['Rolki i shorty','Serie tematyczne','Formaty cykliczne'],points:['Na żywo: rozmowy i przebitki, pomysły rozwijane na planie.','Ze scenariuszem: tematy i przebieg filmów ustalone wcześniej.','Pionowe materiały z dźwiękiem i wersjami do wybranych kanałów.'],film:'fanex-social',example:'MAŁY FORMAT, WŁASNY CHARAKTER',result:'Do regularnych publikacji i kampanii w social mediach.'},
miejsce:{number:'04',title:'NIECH POCZUJĄ,<br>JAK TU JEST.',intro:'Pokażcie atmosferę miejsca, energię wydarzenia albo doświadczenie, na które zapraszacie.',formats:['Film o miejscu','Relacja z wydarzenia','Rozmowy i reportaż'],points:['Wnętrza, detale i perspektywa odwiedzających.','Wypowiedzi ludzi i najważniejsze momenty wydarzenia.','Film podsumowujący lub krótkie materiały do dalszej komunikacji.'],film:'praga',example:'MIEJSCE OPOWIEDZIANE OBRAZEM',result:'Na stronę, do zaproszeń i komunikacji po wydarzeniu.'}};
let selectedOffer='produkt';
function setOffer(key){selectedOffer=key;const o=offers[key],f=films.find(f=>f.id===o.film);document.querySelectorAll('[data-offer]').forEach(b=>{const active=b.dataset.offer===key;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1});const panel=document.querySelector('#offer-panel');panel.setAttribute('aria-labelledby','tab-'+key);panel.innerHTML=`<div class="offer-copy"><span class="panel-number">${o.number} / WASZ CEL</span><h3>${o.title}</h3><p>${o.intro}</p><div class="tags">${o.formats.map(t=>`<span>${t}</span>`).join('')}</div><ul>${o.points.map(p=>`<li>${icon('arrow')}<span>${p}</span></li>`).join('')}</ul><p class="offer-result">${o.result}</p></div><button class="offer-example" data-film="${f.id}" aria-label="Obejrzyj ${f.client}: ${f.title}"><img src="${f.image}" alt="Kadr: ${f.title}"><span class="film-shade"></span><span class="example-top">${o.example}</span><div class="example-caption"><span><b>${f.client}</b><strong>${f.title}</strong></span><i class="play">${icon('play')}</i></div></button>`;}
document.querySelectorAll('[data-offer]').forEach((b,i,buttons)=>{b.addEventListener('click',()=>setOffer(b.dataset.offer));b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%buttons.length;if(e.key==='ArrowLeft')n=(i-1+buttons.length)%buttons.length;if(e.key==='Home')n=0;if(e.key==='End')n=buttons.length-1;if(n!==undefined){e.preventDefault();buttons[n].focus();setOffer(buttons[n].dataset.offer)}})});setOffer('produkt');
let filter='all',expanded=false;
function renderFilms(){const all=films.filter(f=>filter==='all'||f.cat.includes(filter)),shown=expanded?all:all.slice(0,6);document.querySelector('#work-grid').innerHTML=shown.map(f=>`<button class="work-card" data-film="${f.id}" aria-label="Obejrzyj ${f.client}: ${f.title}"><div class="work-image"><img src="${f.image}" alt="" loading="lazy"><span class="work-play">${icon('play')}</span><span class="work-tag">${f.format}</span></div><div class="work-caption"><span>${f.client}</span><h3>${f.title}</h3>${icon('external')}</div></button>`).join('');document.querySelector('#results-count').textContent=`${shown.length} / ${all.length} filmów`;const more=document.querySelector('#more');more.hidden=all.length<=6;more.innerHTML=(expanded?'Pokaż mniej':'Więcej realizacji')+icon(expanded?'close':'plus');more.setAttribute('aria-expanded',expanded);}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;expanded=false;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));renderFilms()}));document.querySelector('#more').onclick=()=>{expanded=!expanded;renderFilms()};renderFilms();
const dialog=document.querySelector('#film-dialog');let returnFocus=null;
function closeFilm(){dialog.close();document.querySelector('#player').replaceChildren();document.body.classList.remove('modal-open');returnFocus?.focus({preventScroll:true})}
document.addEventListener('click',e=>{const b=e.target.closest('[data-film]');if(!b)return;const f=b.dataset.film==='showreel'?showreel:films.find(f=>f.id===b.dataset.film);returnFocus=b;document.querySelector('#film-title').textContent=f.title;document.querySelector('#film-meta').textContent=f.client+' / '+f.format;document.querySelector('#film-description').textContent=f.description;document.querySelector('#film-source').href='https://www.youtube.com/watch?v='+f.video;document.querySelector('#film-agency').textContent=f.agency?'Współpraca z agencją: '+f.agency:'';const player=document.querySelector('#player');player.classList.toggle('portrait',!!f.portrait);player.innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${f.video}?autoplay=1&rel=0&playsinline=1" title="${f.client} - ${f.title}" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe>`;document.body.classList.add('modal-open');dialog.showModal();});document.querySelector('#close-film').onclick=closeFilm;dialog.addEventListener('cancel',e=>{e.preventDefault();closeFilm()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeFilm()}});
const sections=document.querySelectorAll('main>section[id]');if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('header nav a').forEach(a=>{const yes=a.getAttribute('href')==='#'+e.target.id;a.classList.toggle('active',yes);if(yes)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}})},{rootMargin:'-20% 0px -55% 0px'});sections.forEach(s=>observer.observe(s));}
